version: "3.8"
services:
  php: 
    # image: php:7.4-apache
    build: .
    ports:
    - 5000:80
    volumes:
    - ./src:/var/www/html

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      # - "MYSQL_DATABASE=pdo_db"
      # - "MYSQL_USER=root"
      # - "MYSQL_PASSWORD=123123"
      # - "MYSQL_ROOT_PASSWORD=123123"

  php-my-admin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80

    links:
      - mysql:db
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 123123

